# This file was auto-generated by Rapiddocs from our API Definition.

from ....core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException


class UnauthorizedError(RapiddocsHTTPException):
    def __init__(self) -> None:
        super().__init__(status_code=401, name="UnauthorizedError")
